In [35]:
import tensorflow as tf

# Define a Conv2D layer
conv_layer = tf.keras.layers.Conv2D(filters=32, kernel_size=(3, 3), input_shape=(64, 64, 3))

# Initialize the layer (build the layer to create weights)
conv_layer.build((None, 64, 64, 3))

# Get the weights and biases
weights, biases = conv_layer.get_weights()

print(f"Weights shape: {weights.shape}")
print(f"Biases shape: {biases.shape}")


Weights shape: (3, 3, 3, 32)
Biases shape: (32,)


In [36]:
import matplotlib.pyplot as pyplot
import numpy
from matplotlib.animation import PillowWriter

def display_pixel_image(grid_size, image):
    grid_size = grid_size
    colors = image
    
    pyplot.figure(figsize=(10, 10))
    pyplot.imshow(colors, extent=[0, grid_size, 0, grid_size])
    pyplot.xticks(numpy.arange(0, grid_size, 1), labels=[])
    pyplot.yticks(numpy.arange(0, grid_size, 1), labels=[])
    pyplot.grid(which="both", color="black", linewidth=0.5)
    pyplot.show()

In [37]:
import cv2
import numpy as np

# Initialize the camera (0 is the default camera)
cap = cv2.VideoCapture(1)

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Check if frame is captured successfully
    if not ret:
        print("Failed to capture image")
        break

    # Convert the frame to a NumPy array
    numpy_image = np.array(frame)

    # display_pixel_image(64, numpy_image)
    # Display the frame
    # cv2.imshow('Camera', frame)


    cv2.imwrite('camera.jpg', numpy_image)

    # Press 'q' to exit the loop
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the camera and close all OpenCV windows
cap.release()
cv2.destroyAllWindows()

# Print the shape of the NumPy array
print(f"Shape of the captured image: {numpy_image.shape}")


Failed to capture image


NameError: name 'numpy_image' is not defined

In [17]:
import tensorflow as tf

# Instantiate the binary cross-entropy loss object
loss_fn = tf.keras.losses.BinaryCrossentropy()

# Example true labels and predicted probabilities
# y_true = [0, 1, 0, 1]
# y_pred = [0.1, 0.9, 0.2, 0.8]
y_true = [0, 0, 0]
y_pred = [-0.009, -0.1009, -0.00109]

# Calculate the loss
loss = loss_fn(y_true, y_pred)

print('Binary Cross-Entropy Loss:', loss.numpy())


Binary Cross-Entropy Loss: -0.0


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Sample data (features and labels)
X_train = [[0.1, 0.2], [0.2, 0.3], [0.3, 0.4], [0.4, 0.]]
y_train = [0, 0, 1, 1]

# Define a simple model
model = Sequential([
    Dense(2, input_dim=2, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model with Binary Crossentropy loss and Adam optimizer
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Define a custom callback to log weights
class WeightLogger(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        weights = model.get_weights()
        print(f'Epoch {epoch+1} weights:')
        for layer_weights in weights:
            print(layer_weights)

# Create an instance of the custom callback
weight_logger = WeightLogger()

# Train the model
model.fit(X_train, y_train, epochs=100, callbacks=[weight_logger])

# Example of how the loss function and optimizer interact:
# - During each epoch, the model predicts labels for the training data.
# - The loss function calculates the error between predictions and true labels.
# - The optimizer updates the model's weights to reduce this error.

# Check the model's performance
loss, accuracy = model.evaluate(X_train, y_train)
print('Loss:', loss)
print('Accuracy:', accuracy)


Epoch 1/100
1/1 [==============================] - ETA: 0s - loss: 0.6600 - accuracy: 0.5000Epoch 1 weights:
[[ 1.0365397  -0.96609044]
 [-0.19139719 -0.43882668]]
[-0.00099995  0.        ]
[[0.8958169]
 [0.3526181]]
[-0.00099996]
1/1 [==============================] - 0s 262ms/step - loss: 0.6600 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - ETA: 0s - loss: 0.6598 - accuracy: 0.5000Epoch 2 weights:
[[ 1.0375397  -0.96609044]
 [-0.19039714 -0.43882668]]
[-0.00199978  0.        ]
[[0.89681697]
 [0.3526181 ]]
[-0.00199973]
1/1 [==============================] - 0s 15ms/step - loss: 0.6598 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - ETA: 0s - loss: 0.6596 - accuracy: 0.5000Epoch 3 weights:
[[ 1.0385399  -0.96609044]
 [-0.1893969  -0.43882668]]
[-0.00299935  0.        ]
[[0.89781725]
 [0.3526181 ]]
[-0.00299919]
1/1 [==============================] - 0s 14ms/step - loss: 0.6596 - accuracy: 0.5000
Epoch 4/100
1/1 [===========================